# Generated by Django 4.0.1 on 2022-01-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrecord',
            options={'ordering': ['-borrowingTime']},
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='returnTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
